import './global.css';
import { loadTalker } from './api/prompt/DocTalker';
export const metadata = {
    title: 'Welcome to medieval-rules-chat',
    description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    await loadTalker();
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
